import './dom-shim.mjs';
const H = await import('./checks/_coop.mjs');
const { enemyRng } = await import('../src/game/Enemy.js');
const { seedWaves } = await import('../src/game/Waves.js');
const audio = (await import('../src/engine/Audio.js')).audio;
enemyRng.seed(31); seedWaves(31, 0);
const { world } = await H.bootWorld({ level: 'colosseum', settings: { quality: 'low', difficulty: 'knight', mode: 'skirmish' } });
const input = H.idleInput();
const said = []; const won = [];
const n = world.notify.bind(world);
world.notify = (t, sub) => { said.push(`${t} — ${sub ?? ''}`); n(t, sub); };
const rw = audio.runWon?.bind(audio);
audio.runWon = (w) => { won.push(w); return rw?.(w); };
let ended = null; world.onGameOver = (s) => { ended = s; };
world.beginSkirmish({ engagements: 2, strength: 10 });
for (let i = 0; i < 30; i++) world.update(1/60, input);
world.player.damage?.(99999, null, 'probe');
for (let i = 0; i < 60 && !world.over; i++) world.update(1/60, input);
console.log('over', world.over, 'won', world.skirmish.won);
console.log('notify lines:', JSON.stringify(said));
console.log('audio.runWon calls:', JSON.stringify(won));
console.log('ended', JSON.stringify(ended));
