import './dom-shim.mjs';
const Cmd = await import('../src/game/Command.js');
await import('../src/game/Levels.js');
const Company = await import('../src/game/Company.js');
const Muster = await import('../src/game/Muster.js');
localStorage.removeItem(Company.KEY); localStorage.removeItem(Muster.KEY);
const r = new Cmd.CommandRoster(Cmd.ARMIES.republic);
for (let i = 0; i < 10; i++) r.enlist('trooper');
r.all[0].award(Cmd.RANKS[2].xp);
Company.keep(r.all, { army: 'republic', deployed: r.all, ground: 'geonosis' });
const sgt = r.all[0].designation;
console.log('before', Company.load('republic').men.find(m=>m.designation===sgt));
const c = Company.appoint('republic', sgt, true, true);
console.log('returned post', c.men.find(m=>m.designation===sgt)?.post);
console.log('reloaded post', Company.load('republic').men.find(m=>m.designation===sgt)?.post);
