import './dom-shim.mjs';
import { readFile } from 'node:fs/promises';
const t0=Date.now();
const root = new URL('../', import.meta.url);
globalThis.__stationFetch = true;
globalThis.fetch = async (url) => { const b = await readFile(new URL(String(url), root)); return { ok:true, arrayBuffer: async()=>b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength) }; };
const { bootWorld, idleInput } = await import('./checks/_coop.mjs');
const S = await import('../src/game/Station.js');
await S.prepareStation();
const { world } = await bootWorld({ level:'station', settings:{mode:'station',level:'station',allies:0}, onWorld:(w)=>{w._stationFloor=40;} });
console.log('boot ms', Date.now()-t0);
const idle=idleInput(); const t1=Date.now();
for(let i=0;i<600;i++) world.update(1/60, idle);
console.log('600 frames ms', Date.now()-t1);
process.exit(0);
